export const MAIL_EVENTS = {
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  EVENT_VALIDATED: 'EVENT_VALIDATED',
  SEND_PROVIDER_NOTIFICATION: 'SEND_PROVIDER_NOTIFICATION',
  SEND_NOTIFICATION_BY_MAIL: 'SEND_NOTIFICATION_BY_MAIL',
  SEND_NEWSLETTER: 'SEND_NEWSLETTER',
};

export const ORDER_EVENTS = {
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
};


export const EVENT_EVENTS = {
  EVENT_VALIDATED: 'EVENT_VALIDATED',
};