name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
      VPS_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}

    strategy:
      matrix:
        node-version: [22.x] # Uses Node.js 22

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn' # Enable caching for Yarn

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Build Project
      run: yarn build

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        script: |
          cd /var/www/titomeet/api

          # Fix Git "dubious ownership" error
          git config --global --add safe.directory /var/www/titomeet/api
          git pull origin main

          # Ensure correct permissions
          export PATH=$(yarn global bin):$PATH

          # Install dependencies and build
          yarn install --frozen-lockfile
          yarn build

          # Restart application with PM2
          pm2 restart titomeet-backend || pm2 start dist/main.js --name titomeet-backend
          pm2 save
