name: Deploy NestJS App

on:
  push:
    branches:
      - main # Or your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Build NestJS app
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            mkdir -p ${{ secrets.DEPLOY_PATH }}
            rm -rf ${{ secrets.DEPLOY_PATH }}/*
            cd ${{ secrets.DEPLOY_PATH }}
            git clone --depth 1 ${{ github.event.repository.ssh_url }} .
            # Install dependencies
            yarn install --frozen-lockfile 
            # Build the project
            yarn build
            # Stop the application
            pm2 stop titomeet-api || true #Stop if it exists.
            pm2 delete titomeet-api || true #Delete if it exists.
            pm2 start dist/main.js --name titomeet-api